---
output: reprex::reprex_document
knit: reprex::reprex_render
---

Notebook to run STURM Ouput.

```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(stringr)

print(paste("Working directory is:", getwd()))

# Loding figures setttings and functions
source("STURM_output/C00_plots.R")

dir <- "simulation"
save_dir <- paste("STURM_output", "figures", dir, sep = "/")
file <- paste(save_dir, "results.csv", sep = "/")
data <- read.csv(file,  check.names = FALSE, stringsAsFactors = FALSE, header = TRUE, row.names = NULL)
data <- data[, -1]

raw_data <- data

data <- data %>%
    mutate(color = "darkgrey") %>%
    mutate(size = 1) %>%
    # remove "S1"
    filter(!grepl("S1", scenario_name))
```



#### Scenarios

##### Histogram - Distribution of key outcomes across scenarios
```{r}
source("STURM_output/C00_plots.R")

column <- "Emission cumulated (GtCO2)"
save_path <- paste(save_dir, "Emission_cumulated_GtCO2.png", sep = "/")
plot_histogram(data, column, save_path)

column <- "Emission (MtCO2)"
save_path <- paste(save_dir, "Emission_MtCO2_2050.png", sep = "/")
plot_histogram(data, column, save_path)

column <- "Delta total cost private (euro/hh/year)"
save_path <- paste(save_dir, "Delta_total_cost_private_euro_hh_year.png", sep = "/")
plot_histogram(data, column, save_path)
```

##### Scatter plot - Relationship between two key outcomes
```{r}
source("STURM_output/C00_plots.R")
x_column <- "Delta total cost private (euro/hh/year)"
y_column <- "Emission cumulated (GtCO2)"
color_column <- "color"
size_column <- "size"

temp <- data %>%
    mutate(color = "darkgrey") %>%
    mutate(size = 1)

colors_scenarios <- c("darkgrey" =  "darkgrey")
save_path <- paste(save_dir, "Delta_total_cost_private_euro_hh_year_vs_Emission_cumulated_GtCO2.png", sep = "/")

scatter_plots(temp,
            x_column,
            y_column,
            color_column,
            colors_scenarios = colors_scenarios,
            size_column,
            save_path = save_path,
            x_label_suffix = "",
            y_label_suffix = "",
            legend_suffix = "",
            y_label = "Emission cumulated (GtCO2)",
            x_label = "Cost (€/hh/year)",
            legend = FALSE,
            presentation = FALSE)

```

```{r}

``` 

```{r}
source("STURM_output/C00_plots.R")

rename_feature <- c("carbon_tax" = "Carbon tax",
    "sub_heat" = "Heat pump subsidies",
    "learning_rate_heat" = "Heat pump learning-by-doing",
    "_remove_barriers_heater" = "Market-failures heating system",
    "_objective_renovation" = "Energy renovation",
    "_realization_rate_renovation" = "Renovation realization rate",
    "_remove_barriers_renovation" = "Market-failures energy renovation")
list_features <- c("carbon_tax", "_objective_renovation",
    "sub_heat", "learning_rate_heat", "_realization_rate_renovation",
    "_remove_barriers_renovation", "_remove_barriers_heater")
scenarios <- data

y <- "Emission cumulated (GtCO2)"
save_path <- paste(save_dir, "sobol_analysis_emission.png", sep = "/")
sobol_figures(scenarios, list_features, y, rename_feature, save_path)

y <- "Space heating consumption (TWh)"
save_path <- paste(save_dir, "sobol_analysis_energy.png", sep = "/")
sobol_figures(scenarios, list_features, y, rename_feature, save_path)

y <- "Delta total cost private (euro/hh/year)"
save_path <- paste(save_dir, "sobol_analysis_cost.png", sep = "/")
sobol_figures(scenarios, list_features, y, rename_feature, save_path)





```

```{r}

# order ascendng by Total_Order column
df <- df %>%
    arrange(Total_Order) %>%
    mutate(Feature = rename_feature[Feature]) %>%
    mutate(Feature = factor(Feature, levels = unique(Feature)))

# make horizontal bar plot of the first order and total order indices

p <- df %>%
    pivot_longer(cols = c(First_Order, Total_Order),
                names_to = "Order_Type", 
                values_to = "Value") %>%
    ggplot(aes(x = Value, y = Feature, fill = Order_Type)) +
    geom_bar(stat = "identity", position = "dodge") +
    message_building_theme +
    theme(axis.title.x = element_blank(),
        axis.title.y = element_blank()) 

save_path <- paste(save_dir, "sobol_analysis.png", sep = "/")
ggsave(save_path, plot = p, width = plot_settings[["width"]],
        height = plot_settings[["height"]],
        dpi = plot_settings[["dpi"]])

scenarios <- data
list_features <- c("carbon_tax", "_objective_renovation",
    "sub_heat", "learning_rate_heat", "_realization_rate_renovation",
    "_remove_barriers_renovation", "_remove_barriers_heater")
y <- "Space heating consumption (TWh)"

df <- manual_sobol_analysis(scenarios, list_features, y)


rename_feature <- c("carbon_tax" = "Carbon tax",
    "sub_heat" = "Heat pump subsidies",
    "learning_rate_heat" = "Heat pump learning-by-doing",
    "_remove_barriers_heater" = "Market-failures heating system",
    "_objective_renovation" = "Energy renovation",
    "_realization_rate_renovation" = "Renovation realization rate",
    "_remove_barriers_renovation" = "Market-failures energy renovation")


# order ascendng by Total_Order column
df <- df %>%
    arrange(Total_Order) %>%
    mutate(Feature = rename_feature[Feature]) %>%
    mutate(Feature = factor(Feature, levels = unique(Feature)))

# make horizontal bar plot of the first order and total order indices

p <- df %>%
    pivot_longer(cols = c(First_Order, Total_Order),
                names_to = "Order_Type", 
                values_to = "Value") %>%
    ggplot(aes(x = Value, y = Feature, fill = Order_Type)) +
    geom_bar(stat = "identity", position = "dodge") +
    message_building_theme +
    theme(axis.title.x = element_blank(),
        axis.title.y = element_blank()) 




```

```{r}
save_path <- paste(save_dir, "sobol_analysis_energy.png", sep = "/")
ggsave(save_path, plot = p, width = plot_settings[["width"]],
        height = plot_settings[["height"]],
        dpi = plot_settings[["dpi"]])
```