---
output: reprex::reprex_document
knit: reprex::reprex_render
---

Notebook to run STURM Ouput.

```{r}
library(tidyverse)

print(paste("Working directory is:", getwd()))

```

### Generate scenarios
```{r}
# first variable is reference scenario
variables <- list(
  "carbon_tax" = as.character(c("", "EUETSII", "EUETS", "social")),
  "_objective_renovation" = as.character(c("", "renovation_endogenous", "deep_renovation_endogenous")),
  "_sub_heat" = as.character(c("", "carbon")),
  "learning_rate_heat" = as.character(c("constant", "")),
  "_realization_rate" = as.character(c(0.5, 1)),
  "_remove_barriers_renovation" = as.character(c(FALSE, TRUE)),
  "_remove_barriers_heater" = as.character(c(FALSE, TRUE))
)

```

```{r}
# Generate all combinations
combinations <- expand.grid(variables, stringsAsFactors = FALSE)

# Add scenario_id and scenario_name columns
combinations <- combinations %>%
  mutate(scenario_id = as.character(row_number()))

# Identify Counterfactual and All policies scenarios
reference_values <- sapply(variables, function(x) x[1])
all_policies_values <- sapply(variables, function(x) x[length(x)])

combinations <- combinations %>%
  rowwise() %>%
  mutate(scenario_name = case_when(
    all(across(everything(), ~ . == reference_values[cur_column()])) ~ "Counterfactual",
    all(across(everything(), ~ . == all_policies_values[cur_column()])) ~ "All policies",
    TRUE ~ paste0("S", scenario_id)
  ))

# Reorder columns to have scenario_id and scenario_name first
combinations <- combinations %>%
  select(scenario_id, scenario_name, everything())
# Write to CSV
write.csv(combinations, "STURM_data/all_scenarios.csv", row.names = FALSE)

```
